name: flutter_bloc_starter_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.4+5




environment:
  sdk: ^3.12.0

dependencies:
  animations: ^2.2.0
  auto_route: ^11.1.0
  dio: ^5.9.2
  dio_http_formatter: ^3.3.1
  dynamic_color: ^1.8.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.7
  flutter_secure_storage: ^10.2.0
  formz: ^0.8.0
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  dio_refresh: ^1.1.0 
  get_it: ^9.2.1
  injectable: ^3.0.0
  internet_connection_checker_plus: ^3.0.0
  hive: ^2.2.3
  json_annotation: ^4.12.0
  logger: ^2.7.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  sentry_dart_plugin: ^3.3.0
  sentry_dio: ^9.20.0
  sentry_flutter: ^9.20.0
  shimmer: ^3.0.0
  slang: ^4.14.0
  slang_flutter: ^4.14.0
  flutter_screenutil: ^5.9.3
  reactive_forms:
  reactive_forms_annotations: ^8.5.0-beta10
  shared_preferences: ^2.5.5
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 
  injectable_generator: ^3.0.2
  freezed: ^3.2.5
  json_serializable: ^6.14.0
  flutter_gen_runner: ^5.14.1
  auto_route_generator: ^10.5.0
  flutter_launcher_icons: ^0.14.4
  package_rename: ^1.10.1
  reactive_forms_generator: ^8.5.0-beta10
  slang_build_runner: ^4.14.0

  
flutter:
  uses-material-design: true
  assets:
    - env/
    - assets/images/splash/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300

flutter_gen:
  output: lib/core/generated/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/splash/logo_dark.png"
  adaptive_icon_foreground:  "assets/images/splash/logo_dark.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash/logo_light.png
  color_dark: "#000000"
  image_dark: assets/images/splash/logo_dark.png
  android_12:
    image: assets/images/splash/android.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash/android.png
    icon_background_color_dark: "#000000"
  fullscreen: true
package_rename_config:
  android:
    app_name: Starter App # (String) The display name of the android app
    package_name: com.baha_test.app # (String) The package name of the android app

  ios:
    app_name: Starter App # (String) The display name of the ios app
    bundle_name: com.baha_test.app # (String) The bundle name of the ios app
    package_name: # (String) The product bundle identifier of the ios app