# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a release App Bundle and upload to Internal track"
  lane :beta do
    # You can call flutter build directly
    sh("flutter build appbundle --release")
    
    # Upload the generated .aab to Google Play
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end

  lane :beta_github do
    # 1. Fetch the highest active version code from Google Play
    live_codes = google_play_track_version_codes(
      package_name: 'com.baha_test.app',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'], # Matches your injected env variable
      track: 'internal'
    )
    highest_code = live_codes.max || 0
    next_code = highest_code + 1

    puts "Current highest version code on Play Store: #{highest_code}"
    puts "Next version code to use: #{next_code}"

    # 2. Compile and Sign the AAB in a single step 
    sh(
      "flutter build appbundle " \
      "--release " \
      "--build-name=#{ENV['VERSION_NAME']} " \
      "--build-number=#{next_code} "
    )
    # 3. Upload the newly signed AAB to Google Play Store

    upload_to_play_store(
      track: 'internal',
      json_key_data: ENV["PLAY_STORE_CONFIG_JSON"],
      aab: File.expand_path("../build/app/outputs/bundle/release/app-release.aab"),
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end


  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
