# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a release App Bundle and upload to Internal track"
  lane :beta do
    # You can call flutter build directly
    sh("flutter build appbundle --release")
    
    # Upload the generated .aab to Google Play
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
  
  lane :beta_github do
    keystore_absolute_path = File.expand_path("../app/my-release-key.jks")
    # 1. Compile and Sign the AAB in a single step using injected properties
    build_android_app(
      task: "bundle",
      build_type: "Release",
      print_command: false, # Prevents credentials from leaking into GitHub Action logs
      properties: {
        "android.injected.signing.store.file"     => keystore_absolute_path,
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias"      => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password"   => ENV["KEY_PASSWORD"]
      }
    )

    # 2. Upload the newly signed AAB to Google Play Store
    upload_to_play_store(
      track: 'internal',
      json_key_data: ENV["PLAY_STORE_CONFIG_JSON"],
      aab: Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH],

      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end


  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
