# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a release App Bundle and upload to Internal track"
  lane :beta do
    # You can call flutter build directly
    sh("flutter build appbundle --release")
    
    # Upload the generated .aab to Google Play
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
  
  lane :local_p do
    # Points directly to the local.properties file inside the android/ folder
    properties_path2 = File.expand_path("../../local.properties", __FILE__)
    properties_path = File.expand_path("../local.properties", __FILE__)
    puts "Looking for local.properties at path: #{properties_path}"
    puts "Looking for local.properties at path: #{properties_path2}"
    
    version_code = nil
    version_name = nil

    if File.exist?(properties_path)
      File.foreach(properties_path) do |line|
        if line.start_with?("flutter.versionCode=")
          version_code = line.split("=").last.strip
        elsif line.start_with?("flutter.versionName=")
          version_name = line.split("=").last.strip
        end
      end
    else
      UI.error("Could not find local.properties file at path: #{properties_path}")
    end

    puts "========================================"
    puts "Version Code: #{version_code}"
    puts "Version Name: #{version_name}"
    puts "========================================"
  end

  lane :beta_github do
    keystore_absolute_path = File.expand_path("../app/my-release-key.jks")
    
    properties_path = File.expand_path("../local.properties", __FILE__)
    
    version_code = nil
    version_name = nil

    if File.exist?(properties_path)
      File.foreach(properties_path) do |line|
        if line.start_with?("flutter.versionCode=")
          version_code = line.split("=").last.strip
        elsif line.start_with?("flutter.versionName=")
          version_name = line.split("=").last.strip
        end
      end
    else
      UI.error("Could not find local.properties file at path: #{properties_path}")
      puts "========================================"
      puts "cannot find local.properties file at path: #{properties_path}"
      puts "========================================"
    end
    puts "========================================"
    puts "Version Code: #{version_code}"
    puts "Version Name: #{version_name}"
    puts "========================================"

    # 1. Compile and Sign the AAB in a single step using injected properties
    build_android_app(
      task: "bundle",
      build_type: "Release",
      print_command: false, # Prevents credentials from leaking into GitHub Action logs
      properties: {
        "android.injected.signing.store.file"     => keystore_absolute_path,
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias"      => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password"   => ENV["KEY_PASSWORD"],
        "android.injected.bundle.versionCode"     => version_code,
        "android.injected.version.name"           => version_name,
      }
    )

    # 2. Upload the newly signed AAB to Google Play Store

    abb_path = File.expand_path("../../build/app/outputs/bundle/release/app-release.aab", __dir__)
    upload_to_play_store(
      track: 'internal',
      json_key_data: ENV["PLAY_STORE_CONFIG_JSON"],
      aab: File.expand_path("../../build/app/outputs/bundle/release/app-release.aab"),
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end


  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
